FROM rust:1.82 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/jaimervq_xyz_backend .
COPY --from=builder /app/content/ ./content
COPY --from=builder /app/.env .
CMD ["./jaimervq_xyz_backend"]